[Variables]
;COLORSCHEME
Color1=255,255,255,255
Color2=158,209,96,255

;SIDEBAR
SidebarBackground=0,0,0,125
SidebarBorder=25,25,25,100

;SKINS
SkinBackground=0,0,0,1 (set to 0,0,0,1 for transparant+draggable)
SkinBorder=25,25,25,100

;CLOCK
TimeFormat=%H:%M
DateFormat=%A, %#d %B
ClockBackground=255, 255, 255, 0

;SYSTEM
Drive1=C:
Drive2=D:
Drive1Type=HDD
Drive2Type=SSD

;MUSIC PLAYER
MusicPlayer=iTunes

;SOUND
VolumeIncrement=5